### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by nicktcode** [edismooth/ionic2-firebase#2]
Hi

I currently get a build failure when I try to build this project.

```
* What went wrong:

A problem occurred configuring root project 'android'.


Could not find method registerResGeneratingTask() for arguments [task ':processDebugGoogleServices', 
/Users/n/Downloads/ionic2-firebase-master/platforms/android/build/generated/res/google-services/debug] on
 com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated@5921904c.
```

I rechecked everything and can not figure out why I cannot build. Any feedback would be appreciated :)

**Comment by nicktcode** [comment]
I just checked and it happens as soon as I add the cordova-plugin-fcm. Before that I can run the app normaly (without push notification of course)

**Comment by abcnever** [comment]
@nthommen did you figure out what went wrong?
