### ISSUE TITLE
Execution failed for task ':processDebugGoogleServices'.

### ISSUE THREAD

**Issue by mburger81** [edismooth/ionic2-firebase#5]
After doing as described in your readme I got this error

```
Error: /home/abc/abc/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> No matching client found for package name 'com.abc.abc'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

The solution is, you have to set config **<widget id="** in **config.xml** to your **"package_name"** from **google-service.json** you configured in firebird configuration.

Also it is important to know, we have to install from Standalone SDK Manage
- Android Support Repository
- Android Support Library
- Google Play services
- Goggle Repository

I'm not sure if Android Support Library really is need, it is obsolete

![image](https://cloud.githubusercontent.com/assets/3778892/17775378/45c08cf4-6558-11e6-937d-c4cdac6e9bd0.png)

I think it could be useful if you describe this in your readme

**Comment by edismooth** [comment]
@mburger81 Thank you for your solution! I think it could be useful for some users.
