### ISSUE TITLE
while clicking on notification message the app is opened and displays the token instead of message

### ISSUE THREAD

**Issue by jose2007kj** [edismooth/ionic2-firebase#9]
sir first of all i thank you for this project.........sir please tell me where i am going wrong 
notification is displayed correctly but..........when i click on notification the app opens and displays the token instead of message.
also when the notification is received when the app is open.......it displays the token instead of message.

**Comment by Galicaballero** [comment]
Hi Jose,
You need find in code the problem. Notification Push run correctly but you need see a alert in code because these shoe the token. If you speak spanish i can explain better

**Comment by jose2007kj** [comment]
@Galicaballero thanks for replaying...................now i have commented the token alert and its working fine..............and i decided to avoid the need for an alert message if the app is open.
